<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealIngredients extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mealIngredients = [
        ["meal_id" => 1,
        "ingredients" => [["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 71, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 1],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 64, "quantity" => 10]]
        ],[
        "meal_id" => 2,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 71, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 62, "quantity" => 10],
        ],[
        "meal_id" => 5,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 72, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 62, "quantity" => 10],
        ["ingredient_id" => 2, "quantity" => 5],
        ],[
        "meal_id" => 4,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 73, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 62, "quantity" => 10],
        ],[
        "meal_id" => 7,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 71, "quantity" => 30],
        ["ingredient_id" => 74, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 50, "quantity" => 60],
        ["ingredient_id" => 48, "quantity" => 30],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 64, "quantity" => 10],
        ],[
        "meal_id" => 8,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 71, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 32, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 62, "quantity" => 10],
        ],[
        "meal_id" => 10,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 72, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 52, "quantity" => 1],
        ["ingredient_id" => 55, "quantity" => 1],
        ["ingredient_id" => 54, "quantity" => 2],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 5, "quantity" => 5],
        ["ingredient_id" => 6, "quantity" => 5],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 14, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 64, "quantity" => 10],
        ], [
        "meal_id" => 6,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 51, "quantity" => 30],
        ["ingredient_id" => 5, "quantity" => 5],
        ["ingredient_id" => 6, "quantity" => 5],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 14, "quantity" => 1],
        ["ingredient_id" => 12, "quantity" => 5],
        ["ingredient_id" => 58, "quantity" => 45],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 76, "quantity" => 15],
        ], [
        "meal_id" => 9,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 53, "quantity" => 2],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 48, "quantity" => 30],
        ["ingredient_id" => 5, "quantity" => 5],
        ["ingredient_id" => 6, "quantity" => 5],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 14, "quantity" => 1],
        ["ingredient_id" => 12, "quantity" => 5],
        ["ingredient_id" => 61, "quantity" => 5],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 46, "quantity" => 1],
        ],[
        "meal_id" => 3,
        "ingredients" => ["ingredient_id" => 60, "quantity" => 1],
        ["ingredient_id" => 73, "quantity" => 30],
        ["ingredient_id" => 49, "quantity" => 30],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 5, "quantity" => 5],
        ["ingredient_id" => 6, "quantity" => 5],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 57, "quantity" => 5],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 16, "quantity" => 1],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 76, "quantity" => 15],
        ], [
        "meal_id" => 29,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 26, "quantity" => 1],
        ["ingredient_id" => 8, "quantity" => 50],
        ["ingredient_id" => 27, "quantity" => 30],
        ["ingredient_id" => 65, "quantity" => 30],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 63, "quantity" => 10],
        ],[
        "meal_id" => 28,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 28, "quantity" => 1],
        ["ingredient_id" => 66, "quantity" => 30],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 29, "quantity" => 60],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 2, "quantity" => 5],
        ["ingredient_id" => 1, "quantity" => 1],
        ["ingredient_id" => 63, "quantity" => 10],
        ], [
        "meal_id" => 31,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 8, "quantity" => 50],
        ["ingredient_id" => 27, "quantity" => 30],
        ["ingredient_id" => 65, "quantity" => 15],
        ["ingredient_id" => 42, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 5],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 30, "quantity" => 1],
        ["ingredient_id" => 63, "quantity" => 10],
        ],[
        "meal_id" => 30,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 2, "quantity" => 5],
        ["ingredient_id" => 31, "quantity" => 1],
        ["ingredient_id" => 75, "quantity" => 60],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 63, "quantity" => 10],
        ],[
        "meal_id" => 33,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 66, "quantity" => 30],
        ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 2, "quantity" => 5],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 32, "quantity" => 1],
        ["ingredient_id" => 9, "quantity" => 1],
        ["ingredient_id" => 63, "quantity" => 10],
        ],[
        "meal_id" => 32,
        "ingredients" => ["ingredient_id" => 25, "quantity" => 1],
        ["ingredient_id" => 65, "quantity" => 30],
        ["ingredient_id" => 29, "quantity" => 60],
        ["ingredient_id" => 52, "quantity" => 3],
        ["ingredient_id" => 20, "quantity" => 50],
        ["ingredient_id" => 6, "quantity" => 3],
        ["ingredient_id" => 63, "quantity" => 10],
        ], [
        "meal_id" => 34,
        "ingredients" => ["ingredient_id" => 29, "quantity" => 60],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 52, "quantity" => 5],
        ["ingredient_id" => 20, "quantity" => 50],
        ["ingredient_id" => 6, "quantity" => 3],
        ["ingredient_id" => 21, "quantity" => 10],
        ["ingredient_id" => 13, "quantity" => 5],
        ["ingredient_id" => 68, "quantity" => 15],
        ["ingredient_id" => 63, "quantity" => 10],
        ],[
        "meal_id" => 35,
        "ingredients" => ["ingredient_id" => 29, "quantity" => 60],
        ["ingredient_id" => 19, "quantity" => 5],
        ["ingredient_id" => 15, "quantity" => 5],
        ["ingredient_id" => 63, "quantity" => 10],
        ["ingredient_id" => 69, "quantity" => 20],
        ], [
        "meal_id" => 36,
        "ingredients" => ["ingredient_id" => 10, "quantity" => 1],
        ["ingredient_id" => 18, "quantity" => 5],
        ["ingredient_id" => 2, "quantity" => 5],
        ["ingredient_id" => 1, "quantity" => 1],
        ["ingredient_id" => 67, "quantity" => 20],
        ["ingredient_id" => 6, "quantity" => 3],
        ["ingredient_id" => 34, "quantity" => 1],
        ["ingredient_id" => 3, "quantity" => 50],
        ["ingredient_id" => 5, "quantity" => 50],
        ["ingredient_id" => 53, "quantity" => 1],
        ], [
        "meal_id" => 11,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 37, "quantity" => 5],
        ["ingredient_id" => 22, "quantity" => 50],
        ["ingredient_id" => 1, "quantity" => 2],
        ["ingredient_id" => 39, "quantity" => 5],
        ["ingredient_id" => 24, "quantity" => 5],
        ], [
        "meal_id" => 15,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 37, "quantity" => 5],
        ["ingredient_id" => 39, "quantity" => 5],
        ["ingredient_id" => 24, "quantity" => 5],
        ["ingredient_id" => 40, "quantity" => 10],
        ], [
        "meal_id" => 13,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 39, "quantity" => 5],
        ["ingredient_id" => 24, "quantity" => 5],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 9, "quantity" => 1],
        ["ingredient_id" => 27, "quantity" => 10],
        ["ingredient_id" => 41, "quantity" => 5],
        ], [
        "meal_id" => 14,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 42, "quantity" => 10],
        ["ingredient_id" => 70, "quantity" => 40],
        ], [
        "meal_id" => 12,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 37, "quantity" => 1],
        ["ingredient_id" => 22, "quantity" => 2],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 27, "quantity" => 10],
        ["ingredient_id" => 11, "quantity" => 2],
        ["ingredient_id" => 43, "quantity" => 5],
        ], [
        "meal_id" => 16,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 37, "quantity" => 1],
        ["ingredient_id" => 22, "quantity" => 2],
        ["ingredient_id" => 11, "quantity" => 2],
        ["ingredient_id" => 43, "quantity" => 5],
        ["ingredient_id" => 44, "quantity" => 40],
        ["ingredient_id" => 45, "quantity" => 20],
        ["ingredient_id" => 65, "quantity" => 20],
        ], [
        "meal_id" => 18,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 22, "quantity" => 10],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 42, "quantity" => 2],
        ["ingredient_id" => 70, "quantity" => 40],
        ["ingredient_id" => 11, "quantity" => 2],
        ["ingredient_id" => 44, "quantity" => 40],
        ], [
        "meal_id" => 20,
        "ingredients" => ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 24, "quantity" => 5],
        ["ingredient_id" => 70, "quantity" => 40],
        ["ingredient_id" => 44, "quantity" => 150],
        ["ingredient_id" => 6, "quantity" => 10],
        ["ingredient_id" => 21, "quantity" => 10],
        ["ingredient_id" => 59, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 3],
        ], [
        "meal_id" => 17,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 22, "quantity" => 10],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 42, "quantity" => 10],
        ["ingredient_id" => 70, "quantity" => 40],
        ["ingredient_id" => 11, "quantity" => 2],
        ["ingredient_id" => 47, "quantity" => 40],
        ], [
        "meal_id" => 19,
        "ingredients" => ["ingredient_id" => 38, "quantity" => 1],
        ["ingredient_id" => 17, "quantity" => 1],
        ["ingredient_id" => 56, "quantity" => 1],
        ["ingredient_id" => 35, "quantity" => 20],
        ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 37, "quantity" => 1],
        ["ingredient_id" => 22, "quantity" => 2],
        ["ingredient_id" => 40, "quantity" => 10],
        ["ingredient_id" => 11, "quantity" => 2],
        ["ingredient_id" => 43, "quantity" => 5],
        ["ingredient_id" => 45, "quantity" => 20],
        ["ingredient_id" => 47, "quantity" => 50],
        ], [
        "meal_id" => 22,
        "ingredients" => ["ingredient_id" => 36, "quantity" => 10],
        ["ingredient_id" => 24, "quantity" => 5],
        ["ingredient_id" => 6, "quantity" => 10],
        ["ingredient_id" => 21, "quantity" => 10],
        ["ingredient_id" => 59, "quantity" => 1],
        ["ingredient_id" => 23, "quantity" => 3],
        ["ingredient_id" => 47, "quantity" => 150],
        ]
        ];

        DB::table('meal_ingredients')->insert($mealIngredients);
    }
}
